import { FaFigma } from 'react-icons/fa6';
import { RiHtml5Line, RiCss3Line, RiJavascriptLine, RiTailwindCssLine, RiReactjsLine, RiNodejsLine, RiFlutterLine, RiNextjsLine } from "react-icons/ri";
import { TbBrandAdobeXd, TbBrandMongodb, TbBrandDjango } from "react-icons/tb";
import { BiLogoPostgresql } from "react-icons/bi";
import { GrDocker } from "react-icons/gr";
import { FaPython } from "react-icons/fa";
import { BsGithub, BsLinkedin, BsTelegram } from 'react-icons/bs';
import { LuMail } from 'react-icons/lu';
import { SiChromewebstore } from 'react-icons/si';


export const textLocalization = {
    // header
    headerStep1En: 'Mr',
    headerStep1Fa: 'آقای',
    headerStep2En: 'Zarei',
    headerStep2Fa: 'زارعی',

    // landing
    welcomeMessageEn: "Hello 👋 I'm Muhammad Ali!",
    welcomeMessageFa: 'سلام 👋 من محمدعلی هستم !',
    jobTitleEn: "🧑‍💻 I'm a Full stack developer.",
    jobTitleFa: '🧑‍💻 من یک توسعه‌دهنده فول‌استک هستم.',
    jobYearEn: '5+ years experience',
    jobYearFa: '۵+ سال تجربه حرفه‌ای',
    jobHeroDescriptionEn: "Full-stack developer with a deep passion for building modern, scalable, and user-centric software. My professional journey began with HTML, CSS, and JavaScript, and quickly expanded into the interactive and dynamic world of the web.On the back-end, I have extensive experience with Node.js and designing efficient, secure RESTful APIs, and I always focus on clean, maintainable architecture. I also use Git professionally for version control.",
    jobHeroDescriptionFa: "توسعه‌دهنده فول‌استک با اشتیاق عمیق به خلق نرم‌افزارهای مدرن، مقیاس‌پذیر و کاربرمحور. مسیر حرفه‌ای‌ام از HTML، CSS و JavaScript آغاز شد و به سرعت به دنیای تعاملی و پویای وب گسترش یافت. در بک‌اند، با Node.js و طراحی RESTful APIهای بهینه و امن تجربه گسترده‌ای کسب کرده‌ام و همواره بر معماری تمیز و قابل نگهداری تمرکز دارم؛ Git را نیز به صورت حرفه‌ای برای مدیریت نسخه‌ها به کار می‌برم.",
    heroProjectsButtonTextEn: 'View Projects',
    heroProjectsButtonTextFa: 'مشاهده پروژه‌ها',
    heroNumbers: [
        {
            value: '+ 5',
            labelEn: 'Years',
            labelFa: 'سال تجربه',
        },
        {
            value: '+ 50',
            labelEn: 'Projects',
            labelFa: 'پروژه موفق',
        },
        {
            value: '+ 20',
            labelEn: 'Clients',
            labelFa: 'مشتری',
        },
    ],
    heroGuidCards: [
        {
            icon: SiChromewebstore,
            titleEn: 'Web Developer',
            titleFa: 'توسعه دهنده وب',
            descriptionEn: '',
            descriptionFa: '',
        }
    ]

}

export const skills = [
    {
        icon: FaFigma,
        enTitle: 'FIGMA',
        faTitle: 'فیگما',
        enDescription: "Figma is a cloud-native, browser-based collaborative interface design platform powered by WebGL and custom C++ vector engine compiled to WebAssembly for high-performance rendering of complex files. It features true real-time multiplayer editing via WebSockets and Operational Transformation for conflict resolution. Core data uses a tree-based .fig structure serialized with Protocol Buffers/FlatBuffers. In 2026, Variables fully support W3C Design Tokens spec with import/export, conditional logic, expressions, and composite tokens. Native slots enable true composable components (similar to Vue slots/React children). Advanced Auto Layout mimics CSS Flexbox + Grid with responsive behaviors tied to variables. Dev Mode provides inspect panel, code snippets, design token visibility, and seamless Code Connect integration. Recent additions include Claude Code to Canvas (MCP server) for importing AI-generated code as editable frames, enhanced branching/versioning, lazy loading for massive files (>50k layers), and AI-assisted prototyping via Figma Make.",
        faDescription: "فیگما یک پلتفرم طراحی رابط کاربری کاملاً ابری و مبتنی بر مرورگر است که از WebGL و موتور وکتوری سفارشی نوشته‌شده با C++ (کامپایل‌شده به WebAssembly) برای رندرینگ سریع و روان فایل‌های پیچیده استفاده می‌کند. قابلیت ویرایش همزمان واقعی (multiplayer) از طریق WebSocket و الگوریتم Operational Transformation برای حل تعارضات تغییرات فراهم شده است. ساختار داده‌ها به صورت درختی (.fig) ذخیره می‌شود و با Protocol Buffers یا FlatBuffers سریالایز می‌گردد. در سال ۲۰۲۶، سیستم Variables پشتیبانی کامل از استاندارد W3C Design Tokens دارد؛ شامل import/export، شرطی‌ها، expressionها و توکن‌های کامپوزیت. ویژگی native slots امکان ساخت کامپوننت‌های modular و composable واقعی را می‌دهد (مشابه slot در Vue یا children در React). Auto Layout پیشرفته حالا منطق responsive واقعی (شبیه flexbox + grid) را پیاده‌سازی کرده و با variables یکپارچه است. Dev Mode پنل inspect، کد اسنیپت، نمایش توکن‌ها و اتصال Code Connect را ارائه می‌دهد. قابلیت‌های جدید شامل Claude Code to Canvas (از طریق MCP server) برای وارد کردن مستقیم کد تولیدشده توسط AI به صورت فریم‌های قابل ویرایش، branching پیشرفته، lazy loading برای فایل‌های بسیار بزرگ و ابزارهای AI مانند Figma Make برای پروتوتایپ سریع است."
    },
    {
        icon: TbBrandAdobeXd,
        enTitle: 'Adobe XD',
        faTitle: 'ادوبی ایکس دی',
        enDescription: "Adobe XD (Experience Design) is a vector-based UI/UX design and prototyping tool launched by Adobe in 2016 as a direct competitor to Sketch and later Figma. It featured a native desktop application (Windows & macOS) with strong focus on wireframing, high-fidelity mockups, interactive prototyping, and basic animation via timeline-based transitions and micro-interactions. XD used a document-based architecture with .xd files, supporting artboards, symbols (similar to components), responsive resize, repeat grid, and auto-animate for prototyping. It integrated deeply with other Adobe tools like Photoshop and Illustrator via copy-paste and asset linking. Collaboration was handled through cloud sharing links, co-editing (added later), and version history. However, as of 2023, following the failed Figma acquisition, Adobe placed XD into maintenance mode — no new major features are developed, only critical bug fixes and security updates continue (last minor release in late 2025). New users can no longer purchase or easily access XD standalone, and Adobe officially recommends migrating to alternatives like Figma for modern collaborative design workflows. In 2026, XD remains usable for existing licensed users but is considered legacy software with no active innovation.",
        faDescription: "ادوبی ایکس‌دی (Adobe XD) ابزاری وکتوری برای طراحی رابط کاربری و تجربه کاربری است که ادوبی در سال ۲۰۱۶ منتشر کرد تا رقیبی برای Sketch و بعداً Figma باشد. این نرم‌افزار دسکتاپ native (ویندوز و macOS) بود و تمرکز اصلی‌اش روی وایرفریم، mockupهای باکیفیت، پروتوتایپ تعاملی و انیمیشن‌های ساده از طریق تایم‌لاین و micro-interactionها قرار داشت. XD از ساختار فایل .xd استفاده می‌کرد و قابلیت‌هایی مثل artboard، symbol (مشابه کامپوننت)، responsive resize، repeat grid و auto-animate داشت. یکپارچگی عمیقی با فتوشاپ و ایلاستریتور از طریق کپی-پیست و لینک asset ارائه می‌داد. همکاری از طریق لینک‌های ابری، co-editing (بعداً اضافه شد) و history نسخه‌ها انجام می‌گرفت. اما از سال ۲۰۲۳ و پس از شکست خرید Figma، ادوبی XD را در حالت maintenance mode قرار داد — دیگر ویژگی عمده جدید اضافه نمی‌شود و فقط باگ‌های بحرانی و آپدیت‌های امنیتی اعمال می‌گردد (آخرین ریلیز کوچک در اواخر ۲۰۲۵). کاربران جدید دیگر نمی‌توانند XD را به صورت standalone بخرند یا به راحتی دسترسی داشته باشند و ادوبی رسماً مهاجرت به ابزارهایی مثل Figma را برای workflowهای مدرن collaborative پیشنهاد می‌کند. در سال ۲۰۲۶، XD هنوز برای کاربران قدیمی با لایسنس قابل استفاده است اما به عنوان نرم‌افزار legacy بدون نوآوری فعال شناخته می‌شود."
    },
    {
        icon: RiHtml5Line,
        enTitle: 'HTML',
        faTitle: 'اچ تی ام ال',
        enDescription: "HTML (HyperText Markup Language) is the foundational markup language of the World Wide Web, defining the structure and semantics of web content. As of 2026, HTML is maintained as a **living standard** by WHATWG (no longer versioned like HTML5.0 → HTML5.1), continuously updated with new elements, attributes, and APIs. Core HTML5 features from 2014 remain the backbone: semantic elements (<header>, <nav>, <main>, <article>, <section>, <footer>, <aside>), native multimedia (<video>, <audio>, <track> for subtitles), <canvas> for 2D drawing, <svg> inline support, new input types (date, email, range, search, etc.), <datalist>, <progress>, <meter>, offline capabilities via manifest (though largely replaced by Service Workers), and the <!DOCTYPE html> minimal declaration. In recent years (2024–2026), additions include better accessibility defaults, improved form controls (styleable <select> via appearance: base-select), <dialog> enhancements, popover API integration, <details> as native accordions with exclusive open behavior, and experimental elements like <geolocation> (declarative). HTML works hand-in-hand with CSS (now extremely powerful with if(), masonry, anchor positioning, scroll-driven animations) and JavaScript to build progressive web apps (PWAs), responsive sites, and complex SPAs without plugins. Nearly 100% browser support exists for core HTML5, making it the most universal, accessible, and SEO-friendly technology stack foundation. Deprecated features (e.g., <font>, <center>) are removed or ignored in modern parsers.",
        faDescription: "اچ‌تی‌ام‌ال (HyperText Markup Language) زبان نشانه‌گذاری پایه‌ای وب جهانی است که ساختار و معنای محتوای صفحات وب را تعریف می‌کند. تا سال ۲۰۲۶، HTML به صورت **living standard** توسط WHATWG نگهداری می‌شود (بدون نسخه‌بندی مثل HTML5.0 یا HTML5.1) و به طور مداوم با المان‌ها، ویژگی‌ها و APIهای جدید به‌روزرسانی می‌گردد. ویژگی‌های اصلی HTML5 از سال ۲۰۱۴ همچنان هسته اصلی هستند: المان‌های معنایی (<header>، <nav>، <main>، <article>، <section>، <footer>، <aside>)، چندرسانه‌ای native (<video>، <audio>، <track> برای زیرنویس)، <canvas> برای رسم 2D، پشتیبانی inline از <svg>، انواع جدید input (date، email، range، search و غیره)، <datalist>، <progress>، <meter>، قابلیت آفلاین (manifest که حالا عمدتاً با Service Workers جایگزین شده) و宣言 ساده <!DOCTYPE html>. در سال‌های اخیر (۲۰۲۴–۲۰۲۶) اضافه‌شده‌ها شامل بهبودهای دسترسی‌پذیری پیش‌فرض، کنترل‌های فرم بهتر (styleable <select> با appearance: base-select)، بهبود <dialog>، ادغام popover API، <details> به عنوان آکاردئون native با رفتار exclusive open و المان‌های آزمایشی مثل <geolocation> declarative هستند. HTML با CSS (که حالا بسیار قدرتمند شده با if()، masonry، anchor positioning، scroll-driven animations) و JavaScript همکاری می‌کند تا اپ‌های وب پیش‌رونده (PWA)، سایت‌های responsive و SPAهای پیچیده بدون پلاگین ساخته شوند. پشتیبانی تقریباً ۱۰۰٪ مرورگرها از هسته HTML5 وجود دارد و آن را به پایه‌ای جهانی، دسترسی‌پذیر و دوست‌دار SEO تبدیل کرده است. ویژگی‌های منسوخ (مثل <font>، <center>) در پارس‌کننده‌های مدرن حذف یا نادیده گرفته می‌شوند."
    },
    {
        icon: RiCss3Line,
        enTitle: 'CSS',
        faTitle: 'سی اس اس',
        enDescription: "CSS (Cascading Style Sheets) is the core language for styling and layout on the web, defining presentation, visual design, and increasingly interactive behavior. As a living standard maintained by the CSS Working Group (W3C), CSS evolves continuously without fixed versions. By February 2026, CSS has reached unprecedented power, often replacing JavaScript for UI patterns. Key modern features include: Container Queries (size, style, state) for component-level responsiveness; Anchor Positioning for popover/tooltips without JS (death of Popper.js); Scroll-Driven Animations and @scroll-timeline for scroll-linked effects; View Transitions API for smooth page/state changes; :has() relational pseudo-class; advanced nesting (& rules); subgrid for aligned nested grids; masonry layouts (now via grid-lanes or flow-tolerance in emerging specs); if() function for conditional values; sibling-index()/sibling-count() for staggering; customizable <select> with appearance: base-select and ::picker(); scroll-state() queries (@container scroll-state()); popover API enhancements; light-dark() color function; relative color syntax; @property for custom properties with types; and more. These enable zero-JS carousels, native accordions, dynamic theming, interest-based invokers, and complex layouts. Nearly full cross-browser support (Chrome, Firefox, Safari, Edge) exists for most Baseline 2024–2025 features, with Interop 2026 pushing even more alignment. CSS now handles logic, state, and animation natively, making it a true programming-like layer for the web.",
        faDescription: "سی‌اس‌اس (Cascading Style Sheets) زبان اصلی برای استایل‌دهی، چیدمان و طراحی بصری وب است و به طور فزاینده‌ای رفتار تعاملی را هم مدیریت می‌کند. این زبان استاندارد زنده‌ای است که توسط گروه کاری CSS (W3C) نگهداری می‌شود و بدون نسخه‌بندی ثابت، به طور مداوم تکامل می‌یابد. تا فوریه ۲۰۲۶، CSS به قدرتی بی‌سابقه رسیده و اغلب جایگزین جاوااسکریپت برای الگوهای UI شده است. ویژگی‌های کلیدی مدرن شامل: Container Queries (size، style، state) برای responsive بودن در سطح کامپوننت؛ Anchor Positioning برای popover و tooltip بدون JS (مرگ Popper.js)؛ Scroll-Driven Animations و @scroll-timeline برای انیمیشن‌های وابسته به اسکرول؛ View Transitions برای تغییرات نرم صفحه/حالت؛ :has() برای انتخاب رابطه‌ای؛ nesting پیشرفته؛ subgrid برای گریدهای هم‌تراز تو در تو؛ masonry layouts (حالا با grid-lanes یا flow-tolerance در مشخصات جدید)؛ تابع if() برای شرطی‌سازی مقادیر؛ sibling-index() و sibling-count() برای stagger کردن؛ customizable <select> با appearance: base-select و ::picker()؛ queryهای scroll-state()؛ بهبودهای popover API؛ تابع light-dark() برای رنگ؛ relative color syntax؛ @property برای تعریف custom property با نوع؛ و موارد بیشتر هستند. این‌ها امکان ساخت carousel بدون JS، آکاردئون native، تمینگ دینامیک، invokerهای مبتنی بر علاقه و چیدمان‌های پیچیده را فراهم می‌کنند. پشتیبانی تقریباً کامل مرورگرها (کروم، فایرفاکس، سافاری، اج) برای اکثر ویژگی‌های Baseline ۲۰۲۴–۲۰۲۵ وجود دارد و Interop 2026 هم‌راستایی بیشتری را پیش می‌برد. CSS حالا منطق، حالت و انیمیشن را به صورت native مدیریت می‌کند و به لایه‌ای برنامه‌نویسی‌مانند برای وب تبدیل شده است."
    },
    {
        icon: RiTailwindCssLine,
        enTitle: 'TAILWIND CSS',
        faTitle: 'تیلویند',
        enDescription: "Tailwind CSS is a utility-first CSS framework for rapidly building custom user interfaces directly in HTML without leaving your markup. As of February 2026, the current stable version is v4.2 (released mid-February 2026), powered by the high-performance Oxide engine (written in Rust) that delivers 2–5× faster builds, near-instant incremental compilation, and tiny output sizes. Tailwind v4 shifted to a **CSS-first configuration** using native CSS directives like @theme for defining design tokens (colors, spacing, fonts, shadows, etc.) with full CSS custom properties support, @utility for custom classes, and no more tailwind.config.js requirement in most cases. Key modern features include native container queries (@container), color-mix() for dynamic blending, full logical properties (inset-block, padding-inline, etc.), new default color palettes (mauve, olive, mist, taupe), 3D transform utilities, text shadows, masks, field-sizing, inert support, wide-gamut P3 colors, and seamless integration with latest CSS advancements like cascade layers and modern color functions. It supports dark mode via class/media, arbitrary values (e.g., bg-[#123456]/50), variants (hover, focus, lg:, @sm:, etc.), and plugins for extended functionality. Tailwind excels in rapid prototyping, consistent design systems, AI-assisted coding (perfect for tools like Claude due to inline utilities), and works framework-agnostically (React, Vue, Next.js, Svelte, etc.). With Tailwind Plus offering pre-built responsive components, it's the go-to for modern, performant, maintainable styling in 2026.",
        faDescription: "تیلویند سی‌اس‌اس (Tailwind CSS) یک فریم‌ورک CSS utility-first است که امکان ساخت سریع رابط‌های کاربری سفارشی را مستقیماً داخل HTML فراهم می‌کند بدون نیاز به ترک مارک‌آپ. تا فوریه ۲۰۲۶، نسخه پایدار فعلی v4.2 (منتشرشده در اواسط فوریه ۲۰۲۶) است که با موتور Oxide قدرتمند (نوشته‌شده با Rust) کار می‌کند و سرعت بیلد را ۲–۵ برابر افزایش داده، کامپایل افزایشی تقریباً آنی دارد و خروجی بسیار کوچک تولید می‌کند. نسخه ۴ به **پیکربندی CSS-first** منتقل شده و از directiveهای native CSS مثل @theme برای تعریف توکن‌های طراحی (رنگ، فاصله، فونت، سایه و غیره) با پشتیبانی کامل custom properties، @utility برای کلاس‌های سفارشی و حذف نیاز به tailwind.config.js در اکثر موارد استفاده می‌کند. ویژگی‌های کلیدی مدرن شامل container queries native (@container)، color-mix() برای ترکیب دینامیک رنگ، logical properties کامل (inset-block، padding-inline و غیره)، پالت‌های رنگی جدید پیش‌فرض (mauve، olive، mist، taupe)، یوتیلیتی‌های 3D transform، text shadow، mask، field-sizing، inert، رنگ‌های wide-gamut P3 و ادغام کامل با پیشرفت‌های جدید CSS مثل cascade layers و توابع رنگی مدرن است. پشتیبانی dark mode از طریق class/media، مقادیر دلخواه (مثل bg-[#123456]/50)، variantها (hover، focus، lg:، @sm: و غیره) و پلاگین‌ها برای گسترش وجود دارد. تیلویند در پروتوتایپ سریع، سیستم‌های طراحی یکپارچه، کدنویسی با کمک AI (به‌خصوص برای ابزارهایی مثل Claude به دلیل یوتیلیتی‌های inline) عالی عمل می‌کند و با فریم‌ورک‌های مختلف (React، Vue، Next.js، Svelte و غیره) سازگار است. با Tailwind Plus و کامپوننت‌های آماده responsive، در سال ۲۰۲۶ انتخاب اصلی برای استایل‌دهی مدرن، performant و maintainable است."
    },
    {
        icon: RiJavascriptLine,
        enTitle: 'JAVASCRIPT',
        faTitle: 'جاوا اسکریپت',
        enDescription: "JavaScript (ECMAScript) is the dynamic, high-level, interpreted programming language that powers the interactive web, servers (Node.js), mobile apps (React Native), desktop (Electron), and increasingly AI/ML workflows. As a living standard maintained by TC39, it receives annual updates. By February 2026, ECMAScript 2026 (17th edition) is in draft/finalization phase, with many features from 2025 widely supported and new ones landing: Temporal API (precise date/time handling replacing Date quirks), explicit resource management via `using`/`await using` for auto-disposal (files, connections, iterators), `Array.fromAsync()` for async iterables, `Error.isError()` reliable error detection, Uint8Array base64/hex encoding, iterator helpers (map/filter/take/etc.), Set methods (union/intersection/etc.), JSON modules, RegExp.escape(), Promise.try(), Float16Array, and more. Core strengths include first-class functions, prototypes/classes, async/await, Promises, modules (ESM), destructuring, spread/rest, optional chaining, nullish coalescing, BigInt, Symbols, Proxy/Reflect, and modern syntax like arrow functions, template literals, tagged templates. JavaScript runs in nearly every environment via V8 (Chrome/Node), SpiderMonkey (Firefox), JavaScriptCore (Safari), with excellent cross-browser support for ES2025+ features. In 2026, it integrates deeply with TypeScript (now native Go compiler in TS7), frameworks like React (Compiler stable), Angular, Vue/Svelte, and tools like Bun/Deno for faster runtimes. JavaScript remains the most universal language, enabling full-stack development with one codebase, PWAs, WebAssembly interop, and evolving toward safer, more expressive code with less boilerplate.",
        faDescription: "جاوااسکریپت (ECMAScript) زبان برنامه‌نویسی سطح بالا، داینامیک و تفسیری است که وب تعاملی، سرورها (Node.js)، اپ‌های موبایل (React Native)، دسکتاپ (Electron) و حتی workflowهای AI/ML را قدرت می‌دهد. این زبان استاندارد زنده‌ای است که توسط TC39 نگهداری می‌شود و هر سال به‌روزرسانی می‌گردد. تا فوریه ۲۰۲۶، ECMAScript 2026 (ویرایش ۱۷) در مرحله draft/نهایی‌سازی است؛ ویژگی‌های ۲۰۲۵ به طور گسترده پشتیبانی می‌شوند و جدیدها در حال ورودند: Temporal API (مدیریت دقیق تاریخ/زمان جایگزین مشکلات Date)، مدیریت منابع explicit با `using`/`await using` برای dispose خودکار (فایل، اتصال، iterator)، `Array.fromAsync()` برای iterableهای async، `Error.isError()` تشخیص مطمئن خطا، کدگذاری base64/hex برای Uint8Array، iterator helperها (map/filter/take و غیره)، متدهای Set (union/intersection و غیره)، JSON modules، RegExp.escape()، Promise.try()، Float16Array و بیشتر. نقاط قوت اصلی شامل توابع first-class، prototype/class، async/await، Promise، ماژول (ESM)، destructuring، spread/rest، optional chaining، nullish coalescing، BigInt، Symbol، Proxy/Reflect و سینتکس مدرن مثل arrow function، template literal و tagged template است. جاوااسکریپت تقریباً در هر محیطی اجرا می‌شود (V8 در کروم/Node، SpiderMonkey در فایرفاکس، JavaScriptCore در سافاری) با پشتیبانی عالی از ویژگی‌های ES2025+. در ۲۰۲۶، ادغام عمیق با TypeScript (کامپایلر native Go در TS7)، فریم‌ورک‌هایی مثل React (Compiler پایدار)، Angular، Vue/Svelte و ابزارهایی مثل Bun/Deno برای ران‌تایم سریع‌تر دارد. جاوااسکریپت همچنان جهانی‌ترین زبان است و توسعه full-stack با یک codebase، PWA، interop با WebAssembly و حرکت به سمت کد ایمن‌تر و expressiveتر با boilerplate کمتر را ممکن می‌سازد."
    },
    {
        icon: RiNodejsLine,
        enTitle: 'NODE JS',
        faTitle: 'نود جی اس',
        enDescription: "Node.js is an open-source, cross-platform JavaScript runtime built on Chrome's V8 engine, enabling server-side and full-stack JavaScript development since 2009. As of February 2026, the current stable branch is v25.6.1 (Current, released Feb 10, 2026), with v24.x (Krypton) as Active LTS until 2028. Node.js uses an event-driven, non-blocking I/O model powered by libuv, making it exceptionally efficient for I/O-heavy applications like APIs, real-time services, microservices, and streaming. Key modern features in v25+ include: upgraded V8 14.1 for faster JSON parsing/execution and new ES features; native TypeScript type stripping (run .ts files directly without transpilation); built-in base64/hex encoding for Uint8Array; improved permission model; HTTP/3 (QUIC) experimental support; Web Streams API stability; better diagnostics (native --watch, enhanced inspector); experimental WebGPU for AI/ML workloads; and stricter security defaults (memory initialization, TLS fixes). Node.js excels with npm (v11+), ESM as default, worker threads, child processes/clusters for scaling, and native fetch/URLPattern. It powers frameworks like Express, Fastify, NestJS, Hono; databases via native drivers/Prisma/Mongoose; and tools like Bun/Deno for competition. In 2026, Node.js remains the dominant backend runtime for JavaScript/TypeScript ecosystems, offering low-latency, high-concurrency apps with excellent cloud-native fit (serverless, containers).",
        faDescription: "نود.جی‌اس (Node.js) یک ران‌تایم جاوااسکریپت متن‌باز و کراس‌پلتفرم است که بر پایه موتور V8 کروم ساخته شده و از سال ۲۰۰۹ امکان توسعه سمت سرور و فول‌استک با جاوااسکریپت را فراهم کرده است. تا فوریه ۲۰۲۶، شاخه پایدار فعلی v25.6.1 (Current، منتشرشده ۱۰ فوریه ۲۰۲۶) است و v24.x (Krypton) به عنوان Active LTS تا ۲۰۲۸ فعال باقی می‌ماند. نود.جی‌اس از مدل event-driven و non-blocking I/O با libuv استفاده می‌کند که آن را برای اپلیکیشن‌های I/O-heavy مثل APIها، سرویس‌های real-time، میکروسرویس‌ها و استریم بسیار کارآمد می‌سازد. ویژگی‌های کلیدی مدرن در v25+ شامل: ارتقای V8 14.1 برای پارس JSON سریع‌تر و ویژگی‌های جدید ES؛ native TypeScript type stripping (اجرای مستقیم فایل‌های .ts بدون transpilation)؛ کدگذاری base64/hex داخلی برای Uint8Array؛ مدل permission بهبودیافته؛ پشتیبانی آزمایشی HTTP/3 (QUIC)؛ پایداری Web Streams API؛ diagnostics بهتر (native --watch، inspector پیشرفته)؛ WebGPU آزمایشی برای workloadهای AI/ML؛ و امنیت پیش‌فرض سخت‌گیرانه‌تر (ابتدای حافظه، فیکس‌های TLS) است. نود.جی‌اس با npm (v11+)، ESM به عنوان پیش‌فرض، worker threads، child process/cluster برای اسکیل، و native fetch/URLPattern عالی کار می‌کند. این ران‌تایم فریم‌ورک‌هایی مثل Express، Fastify، NestJS، Hono؛ درایورهای native دیتابیس/Prisma/Mongoose و ابزارهایی مثل Bun/Deno را قدرت می‌دهد. در ۲۰۲۶، نود.جی‌اس همچنان غالب‌ترین ران‌تایم بک‌اند در اکوسیستم جاوااسکریپت/تایپ‌اسکریپت است و اپ‌های low-latency، high-concurrency با فیت عالی cloud-native (serverless، کانتینر) ارائه می‌دهد."
    },
    {
        icon: RiReactjsLine,
        enTitle: 'REACT JS',
        faTitle: 'ریکت جی اس',
        enDescription: "React (React.js / ReactJS) is an open-source JavaScript library for building dynamic, component-based user interfaces, maintained by Meta and the community since 2013. As of February 2026, the latest stable version is React 19.2.3 (December 2025 patch), with React 19 series dominating modern development. React 19 introduced groundbreaking features: React Server Components (RSC) for zero-bundle server-rendered components, Server Actions for direct server mutations from client, new hooks like useActionState, useFormStatus, useOptimistic for optimistic UI and form handling, the use() hook for reading promises/resources in render, ref as prop (no forwardRef needed), improved Context (no provider value change propagation issues), document metadata (<title>, <meta>, <link> native), stylesheets/preloading/async scripts support, better error reporting, and the React Compiler (stable in 19+) for automatic memoization/optimization without manual useMemo/useCallback. React 19.2 added Activity API for tracking component lifecycle/activity, useEffectEvent for stable effect callbacks, cacheSignal/Partial Prerendering enhancements, and performance boosts. It uses a fiber reconciler for interruptible rendering, concurrent mode (useTransition, startTransition), Suspense for data fetching, and integrates deeply with frameworks like Next.js (App Router + RSC), Remix, Gatsby. In 2026, React powers most complex UIs with excellent ecosystem (React Native, React Three Fiber, Zustand/Redux/Jotai), TypeScript-first defaults, and AI-assisted coding compatibility. Nearly universal adoption, strong accessibility focus, and continuous evolution make it the de-facto standard for declarative UI development.",
        faDescription: "ریکت (React.js / ReactJS) یک کتابخانه جاوااسکریپت متن‌باز برای ساخت رابط‌های کاربری پویا و مبتنی بر کامپوننت است که از سال ۲۰۱۳ توسط متا و جامعه نگهداری می‌شود. تا فوریه ۲۰۲۶، آخرین نسخه پایدار React 19.2.3 (پچ دسامبر ۲۰۲۵) است و سری React 19 غالب توسعه مدرن شده. React 19 ویژگی‌های انقلابی آورد: React Server Components (RSC) برای کامپوننت‌های سرور بدون باندل کلاینت، Server Actions برای mutation مستقیم سرور از کلاینت، هوک‌های جدید useActionState، useFormStatus، useOptimistic برای UI optimistic و مدیریت فرم، هوک use() برای خواندن promise/resource در رندر، ref به عنوان prop معمولی (بدون نیاز به forwardRef)، Context بهبودیافته (بدون مشکل انتشار تغییر value)، پشتیبانی native از metadata سند (<title>، <meta>، <link>)، stylesheets/preloading/async scripts، گزارش خطای بهتر و React Compiler (پایدار در ۱۹+) برای memoization/بهینه‌سازی خودکار بدون useMemo/useCallback دستی. React 19.2 API Activity برای track کردن lifecycle/activity کامپوننت، useEffectEvent برای callbackهای پایدار effect، بهبودهای cacheSignal/Partial Prerendering و boost عملکرد اضافه کرد. ریکت از fiber reconciler برای رندرینگ interruptible، concurrent mode (useTransition، startTransition)، Suspense برای data fetching استفاده می‌کند و با فریم‌ورک‌هایی مثل Next.js (App Router + RSC)، Remix، Gatsby ادغام عمیق دارد. در ۲۰۲۶، ریکت بیشتر UIهای پیچیده را قدرت می‌دهد با اکوسیستم عالی (React Native، React Three Fiber، Zustand/Redux/Jotai)، پیش‌فرض TypeScript-first و سازگاری با کدنویسی AI. پذیرش تقریباً جهانی، تمرکز قوی روی دسترسی‌پذیری و تکامل مداوم، آن را به استاندارد واقعی توسعه declarative UI تبدیل کرده است."
    },
    {
        icon: RiNextjsLine,
        enTitle: 'NEXT JS',
        faTitle: 'نکست جی اس',
        enDescription: "Next.js is the full-stack React framework by Vercel for building production-grade web applications with server-side rendering, static generation, API routes, and modern rendering patterns. As of February 20, 2026, the latest stable version is Next.js 16.1.6 (LTS branch 16), released in January 2026, with v16.2 canaries actively developed. Next.js 16 (October 2025) introduced major upgrades: explicit caching model (dynamic code runs at request time by default, opt-in with 'use cache'), Cache Components for new programming model, improved Turbopack (now production-stable with incremental computation and faster builds), enhanced routing/caching architecture, better integration with React 19+, Partial Prerendering (PPR) refinements for instant static shells + streamed dynamic content, async request APIs, and agentic/AI-friendly tooling (MCP integration, structured visibility for debugging with agents). It builds on Next.js 15's React 19 support, Turbopack dev stability, staleTimes config, and advanced hydration/error handling. Key strengths: App Router as the primary paradigm (Pages Router legacy), Server Components/Actions for zero-client-JS server logic, built-in optimizations (Image, Font, Script), metadata API, Edge/standalone runtime, and seamless Vercel deployment. In 2026, Next.js dominates full-stack React ecosystems with excellent performance (Core Web Vitals/INP focus), SEO, scalability for SaaS/e-commerce/content sites, TypeScript-first defaults, and deep compatibility with Tailwind, shadcn/ui, tRPC, Prisma, and AI-assisted coding workflows. It remains the de-facto choice for performant, SEO-friendly, dynamic React apps with minimal configuration.",
        faDescription: "نکست.جی‌اس (Next.js) فریم‌ورک فول‌استک ریکت توسط Vercel است که برای ساخت اپلیکیشن‌های وب سطح تولید با رندرینگ سمت سرور، تولید استاتیک، روت‌های API و الگوهای رندرینگ مدرن طراحی شده. تا ۲۰ فوریه ۲۰۲۶، آخرین نسخه پایدار Next.js 16.1.6 (شاخه LTS 16) است که در ژانویه ۲۰۲۶ منتشر شد و کاناری‌های v16.2 در حال توسعه فعال هستند. نکست ۱۶ (اکتبر ۲۰۲۵) ارتقاهای بزرگی آورد: مدل caching explicit (کد داینامیک به طور پیش‌فرض در زمان درخواست اجرا می‌شود، opt-in با 'use cache')، Cache Components برای مدل برنامه‌نویسی جدید، بهبود Turbopack (حالا پایدار برای تولید با incremental computation و بیلدهای سریع‌تر)، معماری routing/caching بهبودیافته، ادغام بهتر با React 19+، بهبود Partial Prerendering (PPR) برای شل استاتیک فوری + محتوای داینامیک streamed، APIهای async request و ابزارهای agentic/AI-friendly (ادغام MCP، visibility ساختاریافته برای دیباگ با ایجنت‌ها). این نسخه بر پایه نکست ۱۵ (پشتیبانی React 19، پایداری Turbopack در dev، staleTimes config و مدیریت hydration/error پیشرفته) ساخته شده. نقاط قوت اصلی: App Router به عنوان پارادایم اصلی (Pages Router legacy)، Server Components/Actions برای منطق سرور بدون JS کلاینت، بهینه‌سازی‌های داخلی (Image، Font، Script)، metadata API، runtime Edge/standalone و دیپلوی seamless روی Vercel. در ۲۰۲۶، نکست.جی‌اس غالب اکوسیستم فول‌استک ریکت است با عملکرد عالی (تمرکز روی Core Web Vitals/INP)، SEO قوی، scalability برای SaaS/فروشگاه/سایت‌های محتوایی، پیش‌فرض TypeScript-first و سازگاری عمیق با Tailwind، shadcn/ui، tRPC، Prisma و workflowهای کدنویسی با کمک AI. همچنان انتخاب اصلی برای اپ‌های ریکت داینامیک، performant و SEO-friendly با حداقل کانفیگ است."
    },
    {
        icon: RiFlutterLine,
        enTitle: 'FLUTTER',
        faTitle: 'فلاتر',
        enDescription: "Flutter is Google's open-source UI toolkit for crafting natively compiled, beautiful applications for mobile, web, desktop, and embedded devices from a single Dart codebase. As of February 20, 2026, the latest stable release is Flutter 3.41 ('Year of the Fire Horse'), launched February 11, 2026, with 868 commits from 145 contributors emphasizing community empowerment and modularity. Key advancements in 3.41 include deeper decoupling of Material and Cupertino libraries into separate packages for independent upgrades and faster design fixes, improved contribution transparency with public release schedules (four stables planned for 2026: 3.41 Feb, 3.44 May, 3.47 Aug, 3.50 Nov), Swift Package Manager & UIScene support on iOS, auto-resizing embedded views, enhanced GPU/Impeller optimizations for smoother rendering, and a refreshed getting-started experience for Flutter & Dart. Flutter uses its own rendering engine (Impeller as default on iOS/macOS, expanding coverage), Skia/Impeller on others, enabling pixel-perfect, 60/120fps UIs with rich animations via the Skia graphics library. Strengths: hot reload (stateful on web stable since earlier releases), declarative widget-based architecture, extensive widget catalog (Material 3 default, Cupertino), built-in accessibility, internationalization, and platform channels/FFI for native integration. In 2026, Flutter excels in cross-platform consistency, performance (especially mobile/desktop), growing web/desktop maturity, AI/ML integration trends, and ecosystem tools (FlutterFlow, Riverpod/Bloc state management). With Dart 3.11, it gains modern language features while maintaining ahead-of-time compilation for native ARM/x64 binaries, making it ideal for high-performance apps without webview compromises.",
        faDescription: "فلاتر (Flutter) کیت‌ابزار UI متن‌باز گوگل است که امکان ساخت اپلیکیشن‌های کامپایل‌شده native و زیبا برای موبایل، وب، دسکتاپ و دستگاه‌های embedded را از یک codebase واحد به زبان Dart فراهم می‌کند. تا ۲۰ فوریه ۲۰۲۶، آخرین نسخه پایدار Flutter 3.41 ('سال اسب آتشین') است که ۱۱ فوریه ۲۰۲۶ منتشر شد و شامل ۸۶۸ کامیت از ۱۴۵ contributor است با تمرکز روی توانمندسازی جامعه و مدولاریتی. پیشرفت‌های کلیدی در ۳.۴۱ شامل جداسازی عمیق‌تر کتابخانه‌های Material و Cupertino به پکیج‌های مستقل برای ارتقای سریع‌تر و فیکس‌های طراحی، شفافیت بیشتر در contribution با برنامه انتشار عمومی (چهار نسخه پایدار در ۲۰۲۶: ۳.۴۱ فوریه، ۳.۴۴ مه، ۳.۴۷ آگوست، ۳.۵۰ نوامبر)، پشتیبانی Swift Package Manager و UIScene در iOS، auto-resizing embedded views، بهینه‌سازی‌های GPU/Impeller برای رندرینگ روان‌تر و تجربه getting-started تازه برای Flutter و Dart است. فلاتر از موتور رندرینگ خودش (Impeller به عنوان پیش‌فرض در iOS/macOS با گسترش پوشش، Skia/Impeller در بقیه) استفاده می‌کند و UIهای pixel-perfect با ۶۰/۱۲۰ فریم انیمیشن غنی ارائه می‌دهد. نقاط قوت: hot reload (stateful روی وب پایدار)، معماری declarative مبتنی بر widget، کاتالوگ گسترده widgetها (Material 3 پیش‌فرض، Cupertino)، دسترسی‌پذیری داخلی، internationalization و platform channels/FFI برای ادغام native. در ۲۰۲۶، فلاتر در consistency کراس‌پلتفرم، عملکرد بالا (به‌خصوص موبایل/دسکتاپ)، بلوغ رو به رشد وب/دسکتاپ، روندهای ادغام AI/ML و ابزارهای اکوسیستم (FlutterFlow، Riverpod/Bloc) عالی عمل می‌کند. با Dart 3.11، ویژگی‌های مدرن زبان را دارد و با AOT compilation باینری‌های native ARM/x64 تولید می‌کند که آن را برای اپ‌های performant بدون compromise webview ایده‌آل می‌سازد."
    },
    {
        icon: FaPython,
        enTitle: 'PYTHON',
        faTitle: 'پایتون',
        enDescription: "Python is a high-level, interpreted, general-purpose programming language emphasizing readability, simplicity, and productivity with its clean syntax and vast ecosystem. As of February 2026, the latest stable release is Python 3.13.2 (released February 4, 2026), with Python 3.14 in alpha/beta stages. Python 3.13 introduced major improvements: experimental free-threaded (no-GIL) mode for true multi-core parallelism (disabled by default, opt-in via --disable-gil or pythont build), JIT compiler (still experimental but showing 20–50% speedups in many workloads), improved error messages with color and suggestions, better REPL with multi-line editing and syntax highlighting, official support for typing.Self and typing.TypeIs, experimental memoryview sub-views, incremental garbage collection refinements, and removal of several deprecated modules/aliases. Core strengths include dynamic typing with optional static type hints (via mypy, pyright, Ruff), extensive standard library ('batteries included'), package management with pip, poetry, uv (extremely fast new resolver/installer), and massive third-party ecosystem (NumPy, Pandas, SciPy for data/science; Django, FastAPI, Flask for web; PyTorch, TensorFlow, JAX for ML/AI; Pytest, Ruff, Black for tooling). In 2026, Python dominates data science, machine learning, AI development (especially with LLMs via LangChain, LlamaIndex, Hugging Face), automation, scripting, DevOps (Ansible, Fabric), scientific computing, and increasingly backend web services with async frameworks. Performance has improved dramatically with faster CPython, PyPy, Cinder, and new runtimes like uvloop/Mojo-inspired experiments, while remaining beginner-friendly and the most taught first language worldwide.",
        faDescription: "پایتون یک زبان برنامه‌نویسی سطح بالا، تفسیری و همه‌منظوره است که با سینتکس تمیز، خوانایی بالا و تمرکز روی بهره‌وری، یکی از محبوب‌ترین زبان‌های جهان شده. تا فوریه ۲۰۲۶، آخرین نسخه پایدار Python 3.13.2 (منتشرشده ۴ فوریه ۲۰۲۶) است و Python 3.14 در مرحله آلفا/بتا قرار دارد. پایتون ۳.۱۳ بهبودهای بزرگی آورد: حالت free-threaded آزمایشی (بدون GIL) برای parallelism واقعی چند هسته‌ای (به طور پیش‌فرض غیرفعال، با --disable-gil یا بیلد pythont فعال می‌شود)، کامپایلر JIT آزمایشی (با speedup ۲۰–۵۰٪ در بسیاری workloadها)، پیام‌های خطای بهبودیافته با رنگ و پیشنهاد، REPL بهتر با ویرایش چندخطی و هایلایت سینتکس، پشتیبانی رسمی typing.Self و typing.TypeIs، sub-view برای memoryview، بهبود incremental GC و حذف چندین ماژول/alias منسوخ است. نقاط قوت اصلی شامل تایپینگ داینامیک با type hint اختیاری (mypy، pyright، Ruff)، کتابخانه استاندارد گسترده ('batteries included')، مدیریت پکیج با pip، poetry، uv (resolver/installer فوق‌سریع جدید) و اکوسیستم عظیم third-party (NumPy، Pandas، SciPy برای داده/علم؛ Django، FastAPI، Flask برای وب؛ PyTorch، TensorFlow، JAX برای ML/AI؛ Pytest، Ruff، Black برای tooling) است. در ۲۰۲۶، پایتون سلطه کامل بر data science، machine learning، توسعه AI (به‌خصوص با LLMها از طریق LangChain، LlamaIndex، Hugging Face)، اتوماسیون، اسکریپتینگ، DevOps (Ansible، Fabric)، محاسبات علمی و روزبه‌روز بیشتر بک‌اند وب با فریم‌ورک‌های async دارد. عملکرد به شدت بهبود یافته با CPython سریع‌تر، PyPy، Cinder و ران‌تایم‌های جدید، در حالی که همچنان beginner-friendly و پراستفاده‌ترین زبان اول دنیا باقی مانده است."
    },
    {
        icon: TbBrandDjango,
        enTitle: 'DJANGO',
        faTitle: 'جنگو',
        enDescription: "Django is a high-level, open-source Python web framework that promotes rapid development, clean design, and the 'Don't Repeat Yourself' (DRY) principle. As of February 20, 2026, the latest stable version is Django 6.0.2 (security patch released February 3, 2026), with Django 6.0 (released December 2025) as the current feature series and Django 5.2 as the active LTS (long-term support until April 2028). Django follows a time-based release cadence (~every 8 months for feature releases). Key strengths include its 'batteries-included' philosophy: built-in ORM (powerful QuerySet API with annotations, aggregations, prefetch_related/select_related), admin interface (auto-generated CRUD with customization), authentication/authorization system, forms (ModelForm, inline formsets), templating engine, internationalization (i18n), caching framework, middleware, class-based views (generic views like ListView, DetailView, CreateView), REST framework integration (via Django REST Framework), async support (ASGI, async views/ORM since 3.1+), and database-agnostic design (PostgreSQL, MySQL, SQLite, Oracle, MariaDB). In recent years (2024–2026), additions include composite primary keys (Django 5.2), improved async handling, better type hints (typing support), facet filters in admin, simplified form rendering templates, Psycopg 3 support, and ongoing security hardening (e.g., February 2026 patches for multiple SQL injection and DoS vulnerabilities in 6.0.2). Django excels in building scalable, secure web applications like content management systems, e-commerce platforms, APIs, SaaS products, and enterprise tools, with excellent documentation, huge community, and ecosystem (Django Packages, channels for real-time, Wagtail/Mezzanine CMS). In 2026, it remains a top choice for Python backend development due to productivity, security defaults, and maturity.",
        faDescription: "جنگو (Django) یک فریم‌ورک وب سطح بالا و متن‌باز پایتون است که توسعه سریع، طراحی تمیز و اصل 'Don't Repeat Yourself' (DRY) را ترویج می‌کند. تا ۲۰ فوریه ۲۰۲۶، آخرین نسخه پایدار Django 6.0.2 (پچ امنیتی منتشرشده ۳ فوریه ۲۰۲۶) است؛ سری ویژگی Django 6.0 (دسامبر ۲۰۲۵) فعلی و Django 5.2 به عنوان LTS فعال (تا آوریل ۲۰۲۸) باقی مانده. جنگو از چرخه انتشار زمان‌محور (~هر ۸ ماه برای فیچر ریلیز) پیروی می‌کند. نقاط قوت اصلی شامل فلسفه 'batteries-included': ORM داخلی قدرتمند (QuerySet با annotation، aggregation، prefetch_related/select_related)، پنل ادمین خودکار CRUD با customization، سیستم احراز هویت/مجوز، فرم‌ها (ModelForm، inline formsets)، موتور قالب، internationalization (i18n)، فریم‌ورک caching، middleware، class-based views (ListView، DetailView، CreateView و غیره)، ادغام REST (با Django REST Framework)، پشتیبانی async (ASGI، async views/ORM از ۳.۱+) و طراحی database-agnostic (PostgreSQL، MySQL، SQLite، Oracle، MariaDB) است. در سال‌های اخیر (۲۰۲۴–۲۰۲۶) اضافه‌شده‌ها شامل composite primary keys (در ۵.۲)، بهبود async، type hint بهتر، facet filters در ادمین، قالب‌های ساده‌تر رندر فرم، پشتیبانی Psycopg 3 و hardening امنیتی (مثل پچ‌های فوریه ۲۰۲۶ برای چندین SQL injection و DoS در ۶.۰.۲) هستند. جنگو در ساخت اپلیکیشن‌های وب scalable و امن مثل CMS، فروشگاه آنلاین، APIها، SaaS و ابزارهای سازمانی عالی عمل می‌کند با داکیومنت فوق‌العاده، جامعه بزرگ و اکوسیستم غنی (Django Packages، channels برای real-time، Wagtail/Mezzanine). در ۲۰۲۶، همچنان یکی از بهترین انتخاب‌ها برای بک‌اند پایتون به دلیل بهره‌وری بالا، امنیت پیش‌فرض و بلوغ است."
    },
    {
        icon: TbBrandMongodb,
        enTitle: 'MONGODB',
        faTitle: 'مانگو دی بی',
        enDescription: "MongoDB is a source-available, cross-platform, document-oriented NoSQL database that stores data in flexible, JSON-like BSON documents with dynamic schemas. As of February 20, 2026, the current stable rapid release is MongoDB 8.2 series (latest patch 8.2.5 released February 10, 2026, EOL March 30, 2026), while the major long-term release is MongoDB 8.0 (GA October 2024, latest patch 8.0.19 February 10, 2026, supported until October 2029). MongoDB 8.0 delivered massive performance gains (up to 36% better reads, 59% faster updates, 200%+ time-series queries vs 7.0), enhanced query optimizer, improved concurrency, better compression, and enterprise features like queryable encryption, column-level encryption, and advanced auditing. Key architecture includes sharding for horizontal scaling, replica sets for high availability (automatic failover), wiredTiger storage engine (default, with zstd/snappy compression), aggregation framework (powerful pipelines with $lookup, $merge, $facet), Atlas Search/Vector Search (full-text, semantic, hybrid, RAG support – now in Community/Enterprise too since 2025), time-series collections optimized for IoT/analytics, change streams for real-time, multi-document ACID transactions (since 4.0), and Atlas as fully managed cloud service on AWS/GCP/Azure with serverless scaling, auto-embedding previews (2026), and Voyage AI integration for better embeddings/reranking. In 2026, MongoDB excels in modern apps: AI/ML (vector DB for semantic search/RAG/agents), real-time analytics, content management, e-commerce, catalogs, and microservices with schema flexibility, developer productivity (mongosh 2.7.0 February 2026), and strong security (CVE fixes ongoing). It remains the most popular document database for scalable, high-performance workloads.",
        faDescription: "مانگو دی‌بی (MongoDB) یک دیتابیس NoSQL سندمحور، کراس‌پلتفرم و source-available است که داده‌ها را در اسناد BSON JSON-مانند با schema داینامیک ذخیره می‌کند. تا ۲۰ فوریه ۲۰۲۶، نسخه پایدار rapid release فعلی سری MongoDB 8.2 (آخرین پچ ۸.۲.۵ منتشرشده ۱۰ فوریه ۲۰۲۶، EOL ۳۰ مارس ۲۰۲۶) و نسخه major بلندمدت MongoDB 8.0 (GA اکتبر ۲۰۲۴، آخرین پچ ۸.۰.۱۹ فوریه ۲۰۲۶، پشتیبانی تا اکتبر ۲۰۲۹) است. MongoDB 8.0 بهبود عملکرد عظیمی آورد (تا ۳۶٪ خواندن بهتر، ۵۹٪ آپدیت سریع‌تر، بیش از ۲۰۰٪ کوئری time-series نسبت به ۷.۰)، بهینه‌ساز کوئری پیشرفته، concurrency بهتر، فشرده‌سازی بهبودیافته و ویژگی‌های سازمانی مثل queryable encryption، column-level encryption و auditing پیشرفته. معماری کلیدی شامل sharding برای اسکیل افقی، replica set برای high availability (failover خودکار)، موتور ذخیره‌سازی wiredTiger (پیش‌فرض با zstd/snappy)، aggregation framework (پایپ‌لاین قدرتمند با $lookup، $merge، $facet)، Atlas Search/Vector Search (full-text، semantic، hybrid، RAG – حالا در Community/Enterprise هم از ۲۰۲۵)، مجموعه‌های time-series بهینه برای IoT/آنالیتیکس، change streams برای real-time، تراکنش ACID چندسندی (از ۴.۰) و Atlas به عنوان سرویس ابری managed با serverless scaling، پیش‌نمایش auto-embedding (۲۰۲۶) و ادغام Voyage AI برای embedding/reranking بهتر است. در ۲۰۲۶، مانگو دی‌بی در اپ‌های مدرن عالی عمل می‌کند: AI/ML (vector DB برای semantic search/RAG/agent)، آنالیتیکس real-time، مدیریت محتوا، فروشگاه آنلاین، کاتالوگ و میکروسرویس با انعطاف schema، بهره‌وری developer (mongosh ۲.۷.۰ فوریه ۲۰۲۶) و امنیت قوی (فیکس CVEهای مداوم). همچنان محبوب‌ترین دیتابیس سندمحور برای workloadهای scalable و performant است."
    },
    {
        icon: BiLogoPostgresql,
        enTitle: 'POSTGRESQL',
        faTitle: 'پست گرس',
        enDescription: "PostgreSQL (often called Postgres) is an open-source, object-relational database management system (ORDBMS) known for its robustness, extensibility, standards compliance (SQL:2023), and advanced features. As of February 20, 2026, the latest minor releases are PostgreSQL 18.2, 17.8, 16.12, 15.16, and 14.21 (released February 12, 2026), with an out-of-cycle patch (18.3, 17.9, etc.) scheduled for February 26, 2026 to fix regressions (including substring() on multi-byte text and CVE-2026-2006 related issues). Supported branches include 18 (until 2030), 17 (until 2029), 16 (until 2028), 15 (until 2027), and 14 (until late 2026). PostgreSQL 18 (September 2025) brought major enhancements like improved vacuum performance, better parallelism, MERGE improvements, new JSON functions, enhanced logical replication (publication/subscription filters), incremental backups, and security hardening. Core architecture features ACID compliance, MVCC (multi-version concurrency control), extensible types/indexes/operators (custom via C/SQL), full-text search (tsvector/tsquery), PostGIS for geospatial, pgvector for vector embeddings/AI (semantic search/RAG), JSON/JSONB with path queries/indexing, window functions, common table expressions (CTE), generated columns, partitioning (declarative, hash/range/list), parallel query execution, WAL-based replication (streaming/physical/logical), point-in-time recovery (PITR), and extensions ecosystem (pgcrypto, hstore, TimescaleDB, Citus for sharding/distributed). In 2026, PostgreSQL excels in mission-critical apps: transactional workloads, analytics (with columnar via extensions), AI/vector DB use cases, geospatial, time-series, and hybrid OLTP/OLAP. It offers excellent performance tuning (shared_buffers, work_mem, autovacuum), strong security (row-level security, SCRAM, certificate auth), and is the gold standard for relational databases with developer-friendly tools (psql, pgAdmin, pgBadger) and cloud-managed options (AWS RDS, Supabase, Neon, Fly.io).",
        faDescription: "پست‌گرس‌کیو‌ال (PostgreSQL یا Postgres) یک سیستم مدیریت پایگاه داده رابطه‌ای-شیءگرا (ORDBMS) متن‌باز است که به دلیل robustness، extensibility، انطباق با استانداردهای SQL:2023 و ویژگی‌های پیشرفته‌اش شناخته می‌شود. تا ۲۰ فوریه ۲۰۲۶، آخرین minor releaseها شامل PostgreSQL 18.2، 17.8، 16.12، 15.16 و 14.21 (منتشرشده ۱۲ فوریه ۲۰۲۶) هستند و یک پچ out-of-cycle (18.3، 17.9 و غیره) برای ۲۶ فوریه ۲۰۲۶ برنامه‌ریزی شده تا regressionها (از جمله substring() روی متن multi-byte و مسائل مرتبط با CVE-2026-2006) را فیکس کند. شاخه‌های پشتیبانی‌شده: ۱۸ (تا ۲۰۳۰)، ۱۷ (تا ۲۰۲۹)، ۱۶ (تا ۲۰۲۸)، ۱۵ (تا ۲۰۲۷) و ۱۴ (تا اواخر ۲۰۲۶). PostgreSQL ۱۸ (سپتامبر ۲۰۲۵) بهبودهای بزرگی آورد مثل vacuum performantتر، parallelism بهتر، بهبود MERGE، توابع JSON جدید، logical replication پیشرفته (فیلتر publication/subscription)، incremental backup و hardening امنیتی. معماری هسته شامل ACID، MVCC، انواع/ایندکس/اپراتور extensible (سفارشی با C/SQL)، full-text search (tsvector/tsquery)، PostGIS برای geospatial، pgvector برای vector embeddings/AI (semantic search/RAG)، JSON/JSONB با path query/indexing، window functions، CTE، generated columns، partitioning declarative (hash/range/list)، parallel query، replication WAL-based (streaming/physical/logical)، PITR و اکوسیستم extension (pgcrypto، hstore، TimescaleDB، Citus برای sharding/distributed) است. در ۲۰۲۶، پست‌گرس در اپ‌های mission-critical عالی است: transactional، analytics (با columnar extensionها)، AI/vector DB، geospatial، time-series و hybrid OLTP/OLAP. عملکرد عالی (shared_buffers، work_mem، autovacuum)، امنیت قوی (row-level security، SCRAM، certificate auth) و ابزارهای developer-friendly (psql، pgAdmin، pgBadger) دارد و گزینه‌های cloud-managed مثل AWS RDS، Supabase، Neon و Fly.io آن را به استاندارد طلایی پایگاه‌های داده رابطه‌ای تبدیل کرده است."
    },
    {
        icon: GrDocker,
        enTitle: 'DOCKER',
        faTitle: 'داکتر',
        enDescription: "Docker is an open-source platform for developing, shipping, and running applications inside lightweight, portable containers. As of February 20, 2026, the latest stable Docker Engine release is 28.0.1 (released February 12, 2026), with Docker Compose v2.30.1 and Docker Desktop 4.38.0 (macOS/Windows/Linux). Docker uses OS-level virtualization via Linux namespaces, cgroups, and union filesystems (overlay2 default) to isolate processes, filesystems, and networks. Core components: Docker daemon (dockerd), CLI (docker), containerd (runtime interface), runc (OCI runtime), BuildKit (advanced builder with cache, secrets, multi-stage, provenance), and Docker Buildx for multi-platform images. Key modern features in 2025–2026 include: improved BuildKit caching (inline cache exports, SBOM/provenance attestations by default), rootless mode enhancements (better cgroup v2 support), containerd 2.0 integration, Docker Scout (software supply chain security with vulnerability scanning, policy enforcement), Compose Watch for live-reloading dev environments, enhanced Compose GPU support, Docker Init for scaffolding projects, better IPv6 dual-stack, confidential containers preview (AMD SEV/Intel TDX), and stronger security defaults (no --privileged by default in many contexts, seccomp/AppArmor profiles). Docker excels in consistent environments (dev = prod parity), microservices, CI/CD pipelines (GitHub Actions, GitLab CI, Jenkins), Kubernetes integration (via containerd/CRI), serverless (AWS Fargate, Azure Container Instances), and edge/IoT deployments. In 2026, it remains the de-facto standard for containerization with excellent ecosystem (Docker Hub, official images, Docker Verified Publishers), multi-arch support (amd64/arm64), and seamless transition to orchestration tools like Kubernetes, Docker Swarm (still maintained), Nomad, or ECS. Docker Desktop now includes Rosetta 2 emulation improvements for Apple Silicon and better WSL2 integration on Windows.",
        faDescription: "داکر (Docker) یک پلتفرم متن‌باز برای توسعه، ارسال و اجرای اپلیکیشن‌ها داخل کانتینرهای سبک و قابل حمل است. تا ۲۰ فوریه ۲۰۲۶، آخرین نسخه پایدار Docker Engine 28.0.1 (منتشرشده ۱۲ فوریه ۲۰۲۶)، Docker Compose v2.30.1 و Docker Desktop 4.38.0 (macOS/Windows/Linux) است. داکر از مجازی‌سازی سطح سیستم‌عامل (Linux namespaces، cgroups، union filesystem مثل overlay2 پیش‌فرض) برای ایزوله کردن پروسس‌ها، فایل‌سیستم و شبکه استفاده می‌کند. اجزای اصلی: دیمن داکر (dockerd)، CLI (docker)، containerd (رابط ران‌تایم)، runc (OCI runtime)، BuildKit (بیلدر پیشرفته با cache، secrets، multi-stage، provenance) و Buildx برای ساخت ایمیج multi-platform. ویژگی‌های کلیدی مدرن ۲۰۲۵–۲۰۲۶ شامل: بهبود caching در BuildKit (inline cache export، SBOM/provenance attestation پیش‌فرض)، rootless mode بهتر (cgroup v2 کامل)، ادغام containerd 2.0، Docker Scout (امنیت زنجیره تأمین با اسکن آسیب‌پذیری و policy)، Compose Watch برای live-reload در dev، پشتیبانی GPU در Compose، Docker Init برای scaffold پروژه، IPv6 dual-stack بهتر، پیش‌نمایش confidential containers (AMD SEV/Intel TDX) و امنیت پیش‌فرض قوی‌تر (عدم --privileged در بسیاری موارد، پروفایل seccomp/AppArmor) است. داکر در ایجاد محیط‌های یکسان (dev = prod)، میکروسرویس‌ها، پایپ‌لاین CI/CD (GitHub Actions، GitLab CI، Jenkins)، ادغام با Kubernetes (از طریق containerd/CRI)، serverless (Fargate، ACI)، و deploymentهای edge/IoT عالی عمل می‌کند. در ۲۰۲۶، همچنان استاندارد اصلی کانتینریزیشن با اکوسیستم فوق‌العاده (Docker Hub، ایمیج‌های رسمی، Verified Publishers)، پشتیبانی multi-arch (amd64/arm64) و انتقال آسان به ابزارهای orchestration مثل Kubernetes، Docker Swarm، Nomad یا ECS است. Docker Desktop حالا بهبودهای Rosetta 2 برای Apple Silicon و ادغام بهتر WSL2 در ویندوز دارد."
    },
]

export const localizationEnTexts = {
    headerLocalStep1: 'Mr',
    headerLocalStep2: 'Zarei',
    welcomeMessage: "Hello 👋 I'm Muhammad Ali!",
    jobTitle: "🧑‍💻 I'm a Full stack developer.",
    jobDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Egestas purus viverra accumsan in nisl nisi Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque In egestas erat imperdiet sed euismod nisi porta lorem mollis Morbi tristique senectus et netus Mattis pellentesque id nibh tortor id aliquet lectus proin',
    guideCard: [
        'Web Developer',
        'Mobile Developer',
        'UI/UX'
    ],
    skillText: 'Skills',
    projectText: 'Projects',
    projectFilter: [
        'All',
        'Web',
        'Mobile',
        'UI/UX',
    ]
}
export const localizationFaTexts = {
    headerLocalStep1: 'آقای',
    headerLocalStep2: 'زارعی',
    welcomeMessage: 'سلام 👋 من محمدعلی هستم !',
    jobTitle: "🧑‍💻 من یک توسعه‌دهنده فول‌استک هستم.",
    jobDescription: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده',
    guideCard: [
        'توسعه دهنده وب',
        'توسعه دهنده موبایل',
        'طراح رابط کاربری'
    ],
    skillText: 'مهارت ها',
    projectText: 'پروژه ها',
    projectFilter: [
        'همه',
        'وب',
        'موبایل',
        'رابط کاربری',
    ]
}

export const footerContents = {
    socialLinks: [
        { icon: BsGithub, href: "https://github.com/mohammadalizarei2003", color: "hover:bg-slate-900" },
        { icon: BsLinkedin, href: "https://www.linkedin.com/in/mohammad-ali-zarei-423488338/", color: "hover:bg-blue-700" },
        { icon: BsTelegram, href: "https://twitter.com/yourusername", color: "hover:bg-sky-500" },
        { icon: LuMail, href: "mailto:hello@example.com", color: "hover:bg-rose-500" }
    ],
    navLinks: [
        { faLabel: "خانه", enLabel: "Home", href: "#" },
        { faLabel: "پروژه‌ها", enLabel: "Projects", href: "#projects" },
        { faLabel: "مهارت‌ها", enLabel: "Skills", href: "#skills" },
        { faLabel: "تماس", enLabel: "Contact", href: "#contact" }
    ]
}
